# Generated by Django 3.2.18 on 2023-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.CharField(default='https://media.istockphoto.com/id/177370583/photo/traffic-cones-and-hardhat-3d-isolated.jpg?s=612x612&w=0&k=20&c=RDDLHMULBB-G_FMMijdavKuVkpYnLIRCbAA1a41r-7o=', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
