# Generated by Django 3.2.18 on 2023-06-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20230523_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
