# Generated by Django 3.2.18 on 2023-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Imagen', models.CharField(blank=True, default='https://www.webempresa.com/foro/wp-content/uploads/wpforo/attachments/3200/318277=80538-Sin_imagen_disponible.jpg', max_length=200)),
            ],
        ),
    ]
