# Generated by Django 3.2.18 on 2023-06-26 14:15

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email_cliente', models.EmailField(max_length=150, null=True, validators=[core.models.validate_email])),
                ('telefono_cliente', models.IntegerField(verbose_name='Teléfono del cliente')),
                ('consulta', models.TextField(max_length=1000, verbose_name='Consulta del cliente')),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
                ('leido', models.IntegerField(choices=[(1, 'No leido'), (2, 'Leido')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Contactos',
                'db_table': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_producto', models.IntegerField(choices=[(1, 'Alimento para Perros'), (2, 'Alimento para Gatos'), (3, 'Accesorios'), (4, 'Juguetes')], default=1)),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Producto')),
                ('unidad', models.IntegerField(choices=[(1, 'Ítem'), (2, '1 kg'), (3, '3 kg'), (4, '7 kg'), (5, '15 kg')], default=1)),
                ('peso_del_animal', models.CharField(default='Ítem', max_length=50, verbose_name='Peso del Animal')),
                ('edad_del_animal', models.IntegerField(default='N/C', verbose_name='Edad del Animal')),
                ('descripcion', models.TextField(verbose_name='Descripción del Producto')),
                ('precio_de_compra', models.IntegerField(default=0, verbose_name='Precio de compra')),
                ('margen_de_ganancias', models.IntegerField(default=2, verbose_name='Margen de ganancias')),
                ('precio_de_venta', models.IntegerField(default=0, verbose_name='Precio de venta')),
                ('en_oferta', models.BooleanField(default=False, verbose_name='En oferta 20%')),
                ('cantidad_en_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('en_stock', models.BooleanField(default=False, verbose_name='En Stock')),
                ('alerta_bajo_stock', models.IntegerField(default=10, verbose_name='Alerta de Cantidad Baja en Stock')),
                ('imagen_producto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen del Producto')),
                ('nombre_del_proveedor', models.TextField(verbose_name='Nombre completo del proveedor')),
                ('contacto_del_proveedor', models.TextField(verbose_name='Nombre completo del contacto del proveedor')),
                ('telefono_proveedor', models.IntegerField(verbose_name='Cel./Tel. del Proveedor')),
                ('email_proveedor', models.EmailField(max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('fecha_de_nacimiento', models.DateField(default=None, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion_particular', models.CharField(max_length=100, verbose_name='Direccion Particular')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad de Residencia')),
                ('codigo_postal', models.CharField(max_length=12, verbose_name='Código Postal')),
                ('telefono', models.IntegerField(verbose_name='Cel./Tel.')),
                ('CUIT', models.IntegerField(verbose_name='C.U.I.T.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Carrito_de_ComprasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productomodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personamodel')),
            ],
            options={
                'verbose_name_plural': 'Carritos de compra',
                'db_table': 'Carrito de Compra',
            },
        ),
    ]
