# Generated by Django 3.2.18 on 2023-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personamodel',
            name='CUIT',
            field=models.IntegerField(blank=True, null=True, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Residencia'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='direccion_particular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Particular'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cel./Tel.'),
        ),
    ]
