# Generated by Django 3.2.18 on 2023-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230626_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactomodel',
            name='consulta',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Consulta del cliente'),
        ),
        migrations.AlterField(
            model_name='contactomodel',
            name='telefono_cliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='alerta_bajo_stock',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Alerta de Cantidad Baja en Stock'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='cantidad_en_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='contacto_del_proveedor',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre completo del contacto del proveedor'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Producto'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='edad_del_animal',
            field=models.IntegerField(blank=True, default='N/C', null=True, verbose_name='Edad del Animal'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='en_oferta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='En oferta 20%'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='en_stock',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='En Stock'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca del Producto'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='margen_de_ganancias',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Margen de ganancias'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='nombre_del_proveedor',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre completo del proveedor'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='peso_del_animal',
            field=models.CharField(blank=True, default='Ítem', max_length=50, null=True, verbose_name='Peso del Animal'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='precio_de_compra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='precio_de_venta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='telefono_proveedor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cel./Tel. del Proveedor'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='tipo_de_producto',
            field=models.IntegerField(blank=True, choices=[(1, 'Alimento para Perros'), (2, 'Alimento para Gatos'), (3, 'Accesorios'), (4, 'Juguetes')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='unidad',
            field=models.IntegerField(blank=True, choices=[(1, 'Ítem'), (2, '1 kg'), (3, '3 kg'), (4, '7 kg'), (5, '15 kg')], default=1, null=True),
        ),
    ]
