# Generated by Django 3.2.18 on 2023-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Producto',
        ),
        migrations.AddField(
            model_name='product',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
