# Generated by Django 3.2.18 on 2023-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_auto_20230603_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.CharField(default='https://www.webempresa.com/foro/wp-content/uploads/wpforo/attachments/3200/318277=80538-Sin_imagen_disponible.jpg', max_length=200, null=True),
        ),
    ]
