# Generated by Django 3.2.18 on 2023-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Imagen',
            field=models.CharField(default='https://www.webempresa.com/foro/wp-content/uploads/wpforo/attachments/3200/318277=80538-Sin_imagen_disponible.jpg', max_length=200),
        ),
    ]
